//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyGo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FamilyGoiteration2_dbEntities1 : DbContext
    {
        public FamilyGoiteration2_dbEntities1()
            : base("name=FamilyGoiteration2_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Suburb> Suburbs { get; set; }
    }
}
