//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public int Id { get; set; }
        public string Education_Sector { get; set; }
        public string School_Type { get; set; }
        public string School_Name { get; set; }
        public string Address_Line_1 { get; set; }
        public string Suburb { get; set; }
        public string Full_Phone_No { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public string Secondary_language { get; set; }
    }
}
